name: FlatDesk-CI/CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_SCSS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          SCSS_CONFIG_FILE: .stylelintrc.json
          HTML_CONFIG_FILE: .htmlhintrc
          ESLINT_CONFIG_FILE: .eslintrc.json

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build Project
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Vercel Deployment
        run: vercel --prod
        env:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          