name: Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.reviewdog-cache  # Replace with the appropriate path for your project
          key: ${{ runner.os }}-reviewdog-${{ hashFiles('**/reviewdog-config.json') }}  # Replace with the appropriate file for hashing
          restore-keys: |
            ${{ runner.os }}-reviewdog-

      - name: Run linters
        run: npm run lint  # Replace with your project's lint command

      - name: Run Reviewdog
        uses: reviewdog/action-eslint@v1  # Replace eslint with your linter
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
