# .github/workflows/super-linter.yml

name: Super-Linter

# Run this workflow every time a new commit is pushed to your repository
on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache Linter Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/super-linter  # Super-Linter cache location
        key: ${{ runner.os }}-super-linter-${{ hashFiles('**/.github/workflows/super-linter.yml') }}
        restore-keys: ${{ runner.os }}-super-linter-

    - name: Lint Code Base
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_SCSS: true
        VALIDATE_HTML: true
        VALIDATE_JAVASCRIPT_ES: true
        DEFAULT_BRANCH: main
        DISABLE_ERRORS: false
        SCSS_CONFIG_FILE: .stylelintrc.json
        HTML_CONFIG_FILE: .htmlhintrc
        ESLINT_CONFIG_FILE: .eslintrc.json
